relative_permalinks: true
redcarpet:
  extensions: [autolink]
# Site settings
title:       brutusin.org
email:       info@brutusin.org
author:      Ignacio del Valle
description: "My personal blog"
baseurl:     ""
url:         "http://brutusin.org"

# Google analytics
google_analytics:

# Optional features
animated:           false
show_related_posts: true
show_post_footers:  true

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname: brutusinorg

# Social icons
show_social_icons: true
github_username: idelvall
stackoverflow_id:
twitter_username: idelvall
google_plus_id:
linkedin_username: idelvall
bitcoin_url:
paypal_url:
flattr_button:

# Build settings
markdown:     redcarpet
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
paginate:     3
sass:
  compressed: true
gems:
  - jekyll-sitemap
